apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "database"
